[package]
name = "nodejs-sys"
version = "0.1.0"
authors = ["Elmar Athmer <elmar@athmer.org>"]
edition = "2018"
build = "build.rs"
categories = ["external-ffi-bindings"]
repository = "https://github.com/zauberpony/nodejs-sys"
license = "MIT"
description = "Native bindings to the nodejs' n-api"

[dependencies]

[build-dependencies]
bindgen = "0.49.0"

[features]
# no features by default
default = []

# enable the experimental API https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html#n_api_usage
experimental = []
